security:
    # Password Hashers
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Providers
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        # Dev firewall for profiler and other resources
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/app-request/login_token
            stateless: true
            json_login:
                check_path: /app-request/login_token
                username_path: email
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        
        # API firewall (JWT Authentication)
        api:
            pattern: ^/api/
            stateless: true
            jwt: ~

        # Main firewall for web access (non-API)
        main:
            user_checker: App\Security\BannedUserChecker
            form_login:
                login_path: login
                check_path: login
                default_target_path: app_home
                failure_path: login
                username_parameter: email
                password_parameter: password

            logout:
                path: logout
                target: app_home

    # Access Control (Secure API endpoints)
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/app-request/login_check, roles: PUBLIC_ACCESS }
        - { path: ^/app-request/register, roles: PUBLIC_ACCESS }
        - { path: ^/api/, roles: IS_AUTHENTICATED_FULLY }

# When testing, the password hasher can be adjusted to speed up tests
when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lower cost for bcrypt
                time_cost: 3 # Lower time cost for argon
                memory_cost: 10 # Lower memory cost for argon
